### ISSUE TITLE
Initialization fails in WP8

### ISSUE THREAD

**Issue by mattisam** [KSemenenko/GoogleAnalyticsForXamarinForms#22]
Hi,
When I call  GoogleAnalytics.Current.Config.TrackingId = trackingId;
in WP8, I experience a crash:

```
System.TypeInitializationException: The type initializer for 'Plugin.GoogleAnalytics.GoogleAnalyticsImplementation' threw an exception. ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Plugin.GoogleAnalytics.DeviceInfo.<ReadFileAsync>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Plugin.GoogleAnalytics.DeviceInfo.ReadFile(String path)
   at Plugin.GoogleAnalytics.PlatformInfoProvider.GetAnonymousClientId()
   at Plugin.GoogleAnalytics.PlatformInfoProvider..ctor(IDeviceInfo deviceInfo)
   at Plugin.GoogleAnalytics.PlatformInfoProvider..ctor()
   at Plugin.GoogleAnalytics.GoogleAnalyticsImplementation..cctor()
   --- End of inner exception stack trace ---
   at Plugin.GoogleAnalytics.GoogleAnalyticsImplementation..ctor()
   at Plugin.GoogleAnalytics.GoogleAnalytics.CreatePluginGoogleAnalytics()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Plugin.GoogleAnalytics.GoogleAnalytics.get_Current()
```

**Comment by KSemenenko** [comment]
Hello! Thanks for your feedback.
Unfortunately I do not have any more wp8 devices, so I can not test it.
Apparently there is something with the file system. I will be grateful for any help.

**Comment by mattisam** [comment]
Ok, I don't have WP8 device either, but I just compiled the software for WP8 and run it in a new device. 

I will try to find time to check this..

**Comment by KSemenenko** [comment]
This is an important point!

**Comment by mattisam** [comment]
This is RM-984_1005, which is Nokia Lumia 830 and it has WP8.1
